# Generated by Django 4.2.1 on 2023-05-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(default="", max_length=200)),
                ("title", models.CharField(blank=True, default="", max_length=40)),
                ("subtitle", models.CharField(blank=True, default="", max_length=100)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "typ",
                    models.CharField(
                        blank=True,
                        choices=[("Quote", "Quote"), ("Event", "Event")],
                        default="Event",
                        max_length=20,
                    ),
                ),
                ("info_link", models.CharField(blank=True, default="", max_length=200)),
                ("sources_link", models.TextField(blank=True, default="")),
                (
                    "video_link",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "video_link2",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("author", models.CharField(blank=True, default="", max_length=200)),
                ("location", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("country", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(blank=True, default="", max_length=20)),
                ("forename", models.CharField(blank=True, default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("author", models.CharField(blank=True, default="", max_length=30)),
                ("text", models.TextField(default="")),
                ("helpText", models.TextField(blank=True, default="")),
                ("date", models.CharField(blank=True, default="", max_length=20)),
                ("context", models.TextField(blank=True, default="")),
                (
                    "typ",
                    models.CharField(
                        blank=True,
                        choices=[("Quote", "Quote"), ("Event", "Event")],
                        default="Quote",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("url", models.URLField()),
            ],
        ),
    ]
