# Generated by Django 4.2.1 on 2023-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="react",
            name="date",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
    ]
