# Generated by Django 4.2.1 on 2023-05-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_body_event_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="sources_link",
            field=models.TextField(blank=True, default=""),
        ),
    ]
