# Generated by Django 4.2.1 on 2023-05-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_react_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(default="", max_length=10)),
                ("title", models.CharField(default="", max_length=40)),
                ("subtitle", models.CharField(default="", max_length=100)),
                ("body", models.TextField(default="")),
                (
                    "typ",
                    models.CharField(
                        choices=[("Quote", "Quote"), ("Event", "Event")], max_length=20
                    ),
                ),
                ("link", models.CharField(default="", max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
