# Generated by Django 4.2.1 on 2023-05-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="author",
            field=models.CharField(default="", max_length=200),
        ),
    ]
