# Generated by Django 4.2.1 on 2023-05-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_event_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.CharField(default="", max_length=200),
        ),
    ]
