# Generated by Django 4.1.2 on 2023-05-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_event_title_alter_quote_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date1", models.DateTimeField(blank=True, null=True)),
                ("date2", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(default="", max_length=200)),
                ("position", models.CharField(default="", max_length=200)),
                ("position_detail", models.TextField(default="")),
                ("description", models.TextField(default="")),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("WE", "Work Experience"),
                            ("Ed", "Education"),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                ("source_list", models.TextField()),
                ("source_to_show", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(default="", max_length=200)),
                ("phone", models.CharField(default="", max_length=200)),
                ("birth", models.DateTimeField(blank=True, null=True)),
                ("location", models.TextField()),
            ],
        ),
    ]
