# Generated by Django 4.1.2 on 2023-07-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_cvitem_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogpost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
            ],
        ),
    ]
