# Generated by Django 4.2.1 on 2023-05-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_event_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="author",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="link",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="event",
            name="typ",
            field=models.CharField(
                blank=True,
                choices=[("Quote", "Quote"), ("Event", "Event")],
                max_length=20,
            ),
        ),
    ]
