# Generated by Django 4.2.1 on 2023-05-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_event_location_alter_event_author_alter_event_body_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="link", new_name="info_link",
        ),
        migrations.AddField(
            model_name="event",
            name="sources_link",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="video_link",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
