# Generated by Django 4.1.2 on 2023-07-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_event_category_quote_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
