# Generated by Django 4.2.1 on 2023-05-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_link_event_info_link_event_sources_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="video_link2",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
